# Generated by Django 3.1.11 on 2021-06-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210620_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='profile_img.jpg', upload_to='profile_user'),
        ),
    ]
