# Generated by Django 3.1.11 on 2021-06-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210620_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address1',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(max_length=1024, null=True, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=1024, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=12, null=True, verbose_name='ZIP / Postal code'),
        ),
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
