# Generated by Django 3.1.11 on 2022-01-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, help_text=' Please enter the Investor Organization/ Company Name.', max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, help_text=' Please enter the Investor Occupation/Business Type.', max_length=255, null=True, verbose_name='Occupation/Business Type'),
        ),
    ]
