# Generated by Django 3.1.11 on 2022-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_investorbankingdetails_investornomineedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='profile_user/profile_img.jpg', upload_to='profile_user'),
        ),
    ]
