# Generated by Django 3.1.11 on 2022-01-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userfcmtoken'),
        ('core', '0008_auto_20220120_1225'),
    ]

    operations = [
    ]
