# Generated by Django 3.1.11 on 2022-03-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_investorinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinformation',
            name='bank_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investorbankingdetails'),
        ),
        migrations.AlterField(
            model_name='investorinformation',
            name='nominiee_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investornomineedetails'),
        ),
    ]
