# Generated by Django 3.1.11 on 2022-03-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220307_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorInformation',
        ),
    ]
