# Generated by Django 3.1.11 on 2022-03-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_investorinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
    ]
