# Generated by Django 3.1.11 on 2022-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220316_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, help_text='Year-Month-Day: YYYY-MM-DD', null=True, verbose_name='Date of Birth'),
        ),
    ]
