# Generated by Django 3.1.11 on 2021-08-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_plugins', '0003_ourcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='generictitledescription',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
