# Generated by Django 3.1.11 on 2021-08-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0004_generictitledescription_is_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_brochure', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='our_company')),
                ('brochure', models.FileField(upload_to='our_company')),
            ],
            options={
                'verbose_name': 'Our Brochure',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
