# Generated by Django 3.1.11 on 2021-08-25 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_plugins', '0005_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderdetails',
            name='description',
            field=models.TextField(verbose_name=[django.core.validators.MinValueValidator(95), django.core.validators.MaxValueValidator(130)]),
        ),
    ]
