# Generated by Django 3.1.11 on 2021-08-25 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_plugins', '0007_auto_20210825_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderdetails',
            name='description',
            field=models.TextField(verbose_name=[django.core.validators.MinLengthValidator(95), django.core.validators.MaxLengthValidator(130)]),
        ),
    ]
