# Generated by Django 3.1.11 on 2021-08-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0009_auto_20210825_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_contactinfopluginmodel', serialize=False, to='cms.cmsplugin')),
                ('first_text', models.CharField(help_text='Enter text', max_length=50)),
                ('second_text', models.CharField(help_text='Enter text', max_length=50)),
            ],
            options={
                'verbose_name': 'Top bar Scroll contact info',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
