# Generated by Django 3.1.11 on 2021-08-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0010_contactinfopluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAndPartnerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_featureandpartnerpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('logo', models.ImageField(upload_to='FeatureAndPartner')),
                ('hover_logo', models.ImageField(upload_to='FeatureAndPartner')),
            ],
            options={
                'verbose_name': 'Feature nad Partner Logo',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
