# Generated by Django 3.1.11 on 2021-08-29 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps_plugins', '0011_featureandpartnerpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureandpartnerpluginmodel',
            name='url',
            field=models.URLField(help_text='Please enter your brand url', null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
