# Generated by Django 3.1.11 on 2021-08-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0012_featureandpartnerpluginmodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardHTMLPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_standardhtmlplugin', serialize=False, to='cms.cmsplugin')),
                ('image', models.ImageField(upload_to='StandardHTMLPlugin')),
                ('head', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Standard HTML content',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
