# Generated by Django 3.1.11 on 2021-09-01 05:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0014_testimonialpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFarmBannerPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_sharedfarmbannerpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('banner_text', models.TextField()),
                ('app_url', models.URLField(help_text='Please enter your app url', null=True, validators=[django.core.validators.URLValidator])),
                ('rotate_img', models.ImageField(upload_to='Sharedfarm_banner')),
                ('front_img', models.ImageField(upload_to='Sharedfarm_banner')),
            ],
            options={
                'verbose_name': 'Shared Farm Banner content',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
