# Generated by Django 3.1.11 on 2021-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aps_plugins', '0015_sharedfarmbannerpluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfarmbannerpluginmodel',
            name='banner_text',
        ),
    ]
