# Generated by Django 3.1.11 on 2021-09-01 08:27

import aps_plugins.models
import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0016_remove_sharedfarmbannerpluginmodel_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfarmbannerpluginmodel',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname=aps_plugins.models.my_placeholder_slotname, to='cms.placeholder'),
        ),
    ]
