# Generated by Django 3.1.11 on 2021-09-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0017_sharedfarmbannerpluginmodel_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTextModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_mytextmodel', serialize=False, to='cms.cmsplugin')),
                ('body', models.TextField(verbose_name='body')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
