# Generated by Django 3.1.11 on 2022-02-23 04:10

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0023_auto_20210905_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_policy', serialize=False, to='cms.cmsplugin')),
                ('head', models.CharField(max_length=200)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Policy',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
