# Generated by Django 3.1.11 on 2022-03-02 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0024_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_footerlinks', serialize=False, to='cms.cmsplugin')),
                ('linkName', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('playstore', 'Google Play Store')], max_length=100, null=True)),
                ('location', models.CharField(blank=True, choices=[('header', 'Header'), ('footer', 'Footer')], max_length=100, null=True)),
                ('linkType', models.CharField(choices=[('internal', 'Internal Link'), ('external', 'External Link'), ('nolink', 'No Link')], max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Header Footer Links and Socials',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
