# Generated by Django 3.1.11 on 2022-02-15 06:53

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aps_plugins', '0024_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True),
        ),
    ]
