# Generated by Django 3.1.11 on 2022-03-23 05:20

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aps_plugins', '0025_footerlinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aps_plugins_terms', serialize=False, to='cms.cmsplugin')),
                ('head', models.CharField(max_length=200)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Terms',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
