# Generated by Django 3.1.11 on 2021-06-17 10:03

import aldryn_apphooks_config.fields
import app_data.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('bn_name', models.CharField(max_length=200, unique=True, verbose_name='Bangla Name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bn_name', models.CharField(max_length=200, verbose_name='Bangla Name')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bn_name', models.CharField(max_length=200, verbose_name='Bangla Name')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[(None, 'Select FAQ category'), ('general', 'FAQ for General'), ('shariah', 'FAQ for Shariah')], default=('general', 'FAQ for General'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedFarmConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('paginate_by', models.PositiveIntegerField(default=5, verbose_name='Paginate size')),
            ],
            options={
                'verbose_name': 'Apphook config',
                'verbose_name_plural': 'Apphook configs',
                'abstract': False,
                'unique_together': {('type', 'namespace')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[(None, 'Select offering category'), ('general', 'General'), ('shariah', 'Shariah')], default='general', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fund_opportunities')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=64, verbose_name='amount')),
                ('duration', models.PositiveIntegerField(help_text=' Please enter the scheme duration in months (max:12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('profit_percentage', models.DecimalField(blank=True, decimal_places=2, help_text=' Please enter the profit return percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='return')),
                ('shariah_profit_from', models.DecimalField(blank=True, decimal_places=2, help_text=' Please enter the probable least profit return percentage ', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='shariah_profit_from')),
                ('shariah_profit_to', models.DecimalField(blank=True, decimal_places=2, help_text=' Please enter the probable max profit return percentage ', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='shariah_profit_to')),
                ('gender', models.CharField(choices=[('cow', 'Cow'), ('bull', 'Bull'), ('heifer', 'Heifer')], max_length=10)),
                ('average_weight', models.DecimalField(decimal_places=2, help_text=' Please enter the average weight in kg eg: 110-120 KG', max_digits=10, verbose_name='average_weight')),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('growth_timeline', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_cows', models.PositiveIntegerField(default=0, help_text=' Please enter the total number of available cows')),
                ('app_config', aldryn_apphooks_config.fields.AppHookConfigField(help_text='When selecting a value, the form is reloaded to get the updated default', on_delete=django.db.models.deletion.CASCADE, to='sharedfarm.sharedfarmconfig')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedfarm.breed', verbose_name='Cattle Breed')),
                ('faq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedfarm.faq')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedfarm.district')),
            ],
            options={
                'verbose_name_plural': 'Funding Opportunities',
                'ordering': ('is_active',),
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_category', to='sharedfarm.faq', verbose_name='Faq Category')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedfarm.division'),
        ),
    ]
