# Generated by Django 3.1.11 on 2021-06-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sharedfarm', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sharedfarm_subscriptionpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharedfarm.subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
