# Generated by Django 3.1.11 on 2021-06-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0003_subscriptionpluginmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpluginmodel',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscriptionpluginmodel',
            name='title',
            field=models.CharField(blank=True, help_text='Optional. Title of the widget.', max_length=64, verbose_name='title'),
        ),
    ]
