# Generated by Django 3.1.11 on 2021-06-27 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharedfarm', '0004_auto_20210622_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Failed'), (3, 'Expired')], db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('txID', models.CharField(blank=True, max_length=200, unique=True)),
                ('bankTxID', models.CharField(blank=True, max_length=200, null=True)),
                ('bankTxStatus', models.CharField(choices=[('CANCEL', 'CANCEL'), ('FAIL', 'FAIL'), ('SUCCESS', 'SUCCESS')], default='CANCEL', max_length=10)),
                ('txnAmount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('spCode', models.CharField(max_length=10, null=True)),
                ('spCodeDes', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentOption', models.CharField(blank=True, max_length=10, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedfarm.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=64, null=True)),
                ('unit', models.IntegerField()),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedfarm.payment')),
                ('product', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_product', to='sharedfarm.product')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
