# Generated by Django 3.1.11 on 2021-08-11 09:24

from django.db import migrations, models
import django.db.models.deletion
import sharedfarm.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0006_auto_20210627_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmsCattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cow_id', models.IntegerField()),
                ('cow_name', models.CharField(max_length=200)),
                ('ear_tag', models.CharField(help_text='Any identification number', max_length=200, verbose_name='Cow Id/ Ear Tag')),
                ('image', models.ImageField(upload_to=sharedfarm.models.cow_image_directory_path)),
                ('farm_id', models.IntegerField()),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_no', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('cow_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedfarm.breed', verbose_name='Cow Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
