# Generated by Django 3.1.11 on 2021-09-02 05:25

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0007_hmscattle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='')),
            ],
        ),
    ]
