# Generated by Django 3.1.11 on 2021-09-02 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0008_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
