# Generated by Django 3.1.11 on 2021-09-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0011_howweworkhead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowWeWorkHead',
        ),
    ]
