# Generated by Django 3.1.11 on 2021-09-02 05:55

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sharedfarm', '0012_delete_howweworkhead'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeWorkHead',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sharedfarm_howweworkhead', serialize=False, to='cms.cmsplugin')),
                ('myfield', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
