# Generated by Django 3.1.11 on 2021-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0013_howweworkhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='howweworkhead',
            name='number_of_steps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
