# Generated by Django 3.1.11 on 2021-09-02 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('sharedfarm', '0014_howweworkhead_number_of_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeWorkStepItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='sharedfarm_howweworkstepitem', serialize=False, to='cms.cmsplugin')),
                ('step_no', models.PositiveIntegerField(blank=True, null=True)),
                ('step_head', models.CharField(blank=True, max_length=200, null=True)),
                ('step_details', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
