# Generated by Django 3.1.11 on 2021-09-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0015_howweworkstepitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howweworkstepitem',
            name='step_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
