# Generated by Django 3.1.11 on 2022-05-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0018_whatsnewbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sharedfarm.payment'),
        ),
    ]
