# Generated by Django 3.1.11 on 2022-05-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharedfarm', '0019_auto_20220519_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
